[pyprland]
plugins = [
  "expose",
  "lost_windows",
  "workspaces_follow_focus",
  "layout_center",
  "toggle_special",
]

[layout_center]
margin = 40
offset = [0,0]
next = "movefocus r"
next2 = "movefocus u"
prev = "movefocus l"
prev2= "movefocus d"
